name: CI Tests

on: [push, pull_request]

jobs:
  black:
    name: Black Code Formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Black Code Formatter
        uses: lgeiger/black-action@master
        with:
          args: >
            SABnzbd.py
            sabnzbd
            scripts
            tools
            builder
            builder/SABnzbd.spec
            tests
            --line-length=120
            --target-version=py38
            --check
            --diff

  test:
    name: Test ${{ matrix.name }} - Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        python-architecture: ["x64"]
        name: ["Linux"]
        os: [ubuntu-20.04]
        include:
          - name: macOS
            os: macos-latest
            python-version: "3.11"
            python-architecture: "x64"
          - name: Windows
            os: windows-latest
            python-version: "3.11"
            python-architecture: "x64"
          - name: Windows (32bit)
            os: windows-latest
            python-version: "3.8"
            python-architecture: "x86"

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }} ${{ matrix.python-architecture }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        architecture:  ${{ matrix.python-architecture }}
    - name: Install system dependencies
      if: runner.os == 'Linux'
      run: sudo apt-get install unrar p7zip-full par2
    - name: Cache Python virtualenv
      uses: syphar/restore-virtualenv@v1.3
      id: cache-virtualenv
      with:
        custom_cache_key_element: ci-${{ matrix.python-architecture }}
        requirement_files: "**/requirements.txt"
    - name: Install Python dependencies
      if: steps.cache-virtualenv.outputs.cache-hit != 'true'
      run: |
        python --version
        python -m pip install --upgrade pip wheel
        pip install --upgrade -r requirements.txt
        pip install --upgrade -r tests/requirements.txt
    - name: Test SABnzbd
      run: pytest -s
